package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTSelf.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTDrawSelf extends ASTStatement {
    // ASTExp srcExp;
    // ASTExp destExp;

  public ASTDrawSelf (ASTExp srcExp, ASTExp destExp) {
      super("DRAW SELF", srcExp, destExp);
      // this.srcExp = srcExp;
      // this.destExp = destExp;
  }
  
  public ASTDrawSelf(ASTExp destExp) {
      this(null, destExp);
  }

  public ASTExp getSrcExp() {
      return (ASTExp) getSubTree(0);
  }

  public ASTExp getDestExp() {
      return (ASTExp) getSubTree(1);
  }
  
  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTDrawSelf(this, state);
  }
  
  @Override
  public String toString() {
      String cmd = getName();
      String destExp = getDestExp().toString();
      ASTExp srcExp = getSrcExp();
      if (srcExp == null) {
          return String.format("%s TO %s", cmd, destExp);
      } else {
          return String.format("%s FROM %s TO %s", cmd, srcExp.toString(), destExp);
      }
  }

}
