package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTExpVar.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTExpPtCCRot extends ASTExp {
  ASTExp angleExp;

  public ASTExpPtCCRot (ASTExp var) {
    this.angleExp = var;
  }

  public ASTExp getAngleExp() {
    return angleExp;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTExpPtCCRot(this, state);
  }
  
  @Override
  public String toString() {
      return String.format("@(%s)", angleExp);
  }

}
