package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTExpVar.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTExpNegate extends ASTExp {
  ASTExp exp;

  public ASTExpNegate (ASTExp exp) {
    this.exp = exp;
  }

  public ASTExp getExp() {
    return exp;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTExpNegate(this, state);
  }
  
  @Override
  public String toString() {
      return String.format("-%s", exp);
  }

}
