
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 24;
  public static final int FROM = 6;
  public static final int PLUS = 20;
  public static final int INT = 25;
  public static final int RPAREN = 16;
  public static final int X_UNIT = 31;
  public static final int EQUAL = 19;
  public static final int HOME = 9;
  public static final int SEMI = 13;
  public static final int CLEAR = 10;
  public static final int NUM_ID = 29;
  public static final int END = 4;
  public static final int Y_UNIT = 32;
  public static final int HERE = 11;
  public static final int LPAREN = 15;
  public static final int COLON = 14;
  public static final int ORIGIN = 30;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int DIV = 23;
  public static final int MINUS = 21;
  public static final int error = 1;
  public static final int POINT_ID = 28;
  public static final int LET = 8;
  public static final int FRACTAL_ID = 27;
  public static final int DRAW = 5;
  public static final int CCROT = 17;
  public static final int LINE = 12;
  public static final int REAL = 26;
  public static final int MUL = 22;
  public static final int SELF = 3;
  public static final int TO = 7;
  public static final int FRACTAL = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FRACTAL",
  "SELF",
  "END",
  "DRAW",
  "FROM",
  "TO",
  "LET",
  "HOME",
  "CLEAR",
  "HERE",
  "LINE",
  "SEMI",
  "COLON",
  "LPAREN",
  "RPAREN",
  "CCROT",
  "COMMA",
  "EQUAL",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "INT",
  "REAL",
  "FRACTAL_ID",
  "POINT_ID",
  "NUM_ID",
  "ORIGIN",
  "X_UNIT",
  "Y_UNIT"
  };
}

